name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - reload-tls
    tags:
      - v*
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [client, server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/qjoly/spiffe-demo-${{ matrix.service }}

      - name: Build and push - Release
        uses: docker/build-push-action@v6
        if:  startsWith(github.event.ref, 'refs/tags/v')
        with:
          context: ${{ matrix.service }}
          push: true
          file: ${{ matrix.service }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push - Dev
        uses: docker/build-push-action@v6
        if:  github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/')
        with:
          context: ${{ matrix.service }}
          push: true
          file: ${{ matrix.service }}/Dockerfile
          tags: ghcr.io/qjoly/spiffe-demo-${{ matrix.service }}:dev

